name: MacOS 11 CI

on:
  push:
    branches: [verification]
  pull_request:
    branches: [verification]

jobs:

  exec-ci:
    runs-on: macos-11

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Reconfigure Package Repo URLs
        run: sed -i '' 's/git@github.com:/https:\/\/${{ secrets.SWIFTFSM_WORKFLOW_PAT }}@github.com\//g' Package.swift

      - name: Run tests
        run: swift test --enable-code-coverage

      - name: Coverage report
        uses: maxep/spm-lcov-action@0.3.1
        with:
          output-file: ./coverage/lcov.info
